export const recentPosts = [
  {
    title: '5 livros para ler quando você precisa de inspiração',
    date: '11 de novembro de 2024',
    summary:
      'Alguns livros têm o poder de nos reconectar com nossas motivações mais profundas. Se você está em busca de uma leitura que reacenda a paixão pela vida, pelas suas metas ou até mesmo pelas pequenas alegrias do cotidiano, esta lista é para você!',
    text: 'Lorem ipsum odor amet, consectetuer adipiscing elit. Eleifend eleifend pharetra sodales sollicitudin cubilia proin dolor neque. Tempor pharetra nisi mollis facilisis vehicula justo condimentum finibus. Velit malesuada posuere massa quis accumsan tempor auctor ultrices. Aliquam porttitor fames maximus, eleifend urna dapibus odio mus ac. Habitasse aliquet convallis condimentum convallis habitant laoreet. Potenti tincidunt praesent posuere turpis nullam pretium.\nBlandit senectus nostra scelerisque ullamcorper, ultricies justo ad egestas. Penatibus pretium aenean ridiculus magnis litora tellus enim. Ad platea habitant porttitor est leo ante ac. Nascetur viverra ex auctor ut, est blandit montes. Senectus porta ac sit hendrerit ridiculus mollis potenti. Justo posuere nulla aenean hac placerat gravida scelerisque. Tellus risus quis vitae tortor interdum. At risus curae curabitur aptent ornare mattis. Proin dictum a parturient, lobortis nostra leo.\nHabitasse nullam senectus quis massa cras, quisque netus dolor. Neque eu tellus praesent magnis suspendisse. Pretium eros cras nullam quisque; sociosqu quisque. Dignissim erat dignissim porta erat senectus habitasse erat arcu. Et proin magnis sem nullam; dictumst ad mollis tincidunt. Id urna dis arcu dignissim eros pellentesque scelerisque tristique magna?\nPulvinar nostra potenti rhoncus; dictum mauris eleifend nec. Dictum in facilisis cras efficitur congue rutrum. Erat maximus lacinia volutpat ante metus lorem mollis taciti. Eleifend convallis efficitur felis orci pretium bibendum? Orci aliquam lobortis pulvinar malesuada elementum dolor auctor. Leo urna ac parturient himenaeos dolor libero ultricies sem.\nLorem cras tempus velit augue auctor tristique odio nibh. Vitae nunc rutrum at pellentesque curae malesuada condimentum. Molestie habitant morbi nascetur eu; tellus platea ad pellentesque. Aliquam interdum adipiscing hendrerit parturient; consectetur erat. Conubia elementum phasellus rhoncus tincidunt euismod. Taciti nunc placerat lacinia ac sodales porttitor. Nascetur ultricies venenatis in et aenean augue ultricies erat accumsan. Lectus inceptos condimentum ad parturient maximus; luctus nullam vulputate. Cras porttitor mollis viverra hendrerit morbi facilisis.',
    image: 'src/assets/inspiration-post.jpg'
  },
  {
    title: 'Por que ainda vale a pena ler Jane Austen?',
    date: '11 de novembro de 2024',
    image: 'src/assets/austen-post.avif',
    summary:
      'Romances clássicos como os de Jane Austen são eternos, mas, com tantas opções de livros modernos, será que ainda vale a pena ler Austen hoje? Neste post, vamos explorar o que torna as histórias da autora tão poderosas e como elas ainda conversam com os dilemas atuais.',
    text: 'Lorem ipsum odor amet, consectetuer adipiscing elit. Eleifend eleifend pharetra sodales sollicitudin cubilia proin dolor neque. Tempor pharetra nisi mollis facilisis vehicula justo condimentum finibus. Velit malesuada posuere massa quis accumsan tempor auctor ultrices. Aliquam porttitor fames maximus, eleifend urna dapibus odio mus ac. Habitasse aliquet convallis condimentum convallis habitant laoreet. Potenti tincidunt praesent posuere turpis nullam pretium.\nBlandit senectus nostra scelerisque ullamcorper, ultricies justo ad egestas. Penatibus pretium aenean ridiculus magnis litora tellus enim. Ad platea habitant porttitor est leo ante ac. Nascetur viverra ex auctor ut, est blandit montes. Senectus porta ac sit hendrerit ridiculus mollis potenti. Justo posuere nulla aenean hac placerat gravida scelerisque. Tellus risus quis vitae tortor interdum. At risus curae curabitur aptent ornare mattis. Proin dictum a parturient, lobortis nostra leo.\nHabitasse nullam senectus quis massa cras, quisque netus dolor. Neque eu tellus praesent magnis suspendisse. Pretium eros cras nullam quisque; sociosqu quisque. Dignissim erat dignissim porta erat senectus habitasse erat arcu. Et proin magnis sem nullam; dictumst ad mollis tincidunt. Id urna dis arcu dignissim eros pellentesque scelerisque tristique magna?\nPulvinar nostra potenti rhoncus; dictum mauris eleifend nec. Dictum in facilisis cras efficitur congue rutrum. Erat maximus lacinia volutpat ante metus lorem mollis taciti. Eleifend convallis efficitur felis orci pretium bibendum? Orci aliquam lobortis pulvinar malesuada elementum dolor auctor. Leo urna ac parturient himenaeos dolor libero ultricies sem.\nLorem cras tempus velit augue auctor tristique odio nibh. Vitae nunc rutrum at pellentesque curae malesuada condimentum. Molestie habitant morbi nascetur eu; tellus platea ad pellentesque. Aliquam interdum adipiscing hendrerit parturient; consectetur erat. Conubia elementum phasellus rhoncus tincidunt euismod. Taciti nunc placerat lacinia ac sodales porttitor. Nascetur ultricies venenatis in et aenean augue ultricies erat accumsan. Lectus inceptos condimentum ad parturient maximus; luctus nullam vulputate. Cras porttitor mollis viverra hendrerit morbi facilisis.'
  },
  {
    title: 'Como montar a estante de livros dos sonhos',
    date: '11 de novembro de 2024',
    image: 'src/assets/library-post.jpg',
    summary:
      'Não basta ter uma estante cheia de livros: ela também pode ser um espaço inspirador, que reflete sua personalidade e paixão por histórias. Que tal aprender algumas dicas para organizar e decorar sua biblioteca particular?',
    text: 'Lorem ipsum odor amet, consectetuer adipiscing elit. Eleifend eleifend pharetra sodales sollicitudin cubilia proin dolor neque. Tempor pharetra nisi mollis facilisis vehicula justo condimentum finibus. Velit malesuada posuere massa quis accumsan tempor auctor ultrices. Aliquam porttitor fames maximus, eleifend urna dapibus odio mus ac. Habitasse aliquet convallis condimentum convallis habitant laoreet. Potenti tincidunt praesent posuere turpis nullam pretium.\nBlandit senectus nostra scelerisque ullamcorper, ultricies justo ad egestas. Penatibus pretium aenean ridiculus magnis litora tellus enim. Ad platea habitant porttitor est leo ante ac. Nascetur viverra ex auctor ut, est blandit montes. Senectus porta ac sit hendrerit ridiculus mollis potenti. Justo posuere nulla aenean hac placerat gravida scelerisque. Tellus risus quis vitae tortor interdum. At risus curae curabitur aptent ornare mattis. Proin dictum a parturient, lobortis nostra leo.\nHabitasse nullam senectus quis massa cras, quisque netus dolor. Neque eu tellus praesent magnis suspendisse. Pretium eros cras nullam quisque; sociosqu quisque. Dignissim erat dignissim porta erat senectus habitasse erat arcu. Et proin magnis sem nullam; dictumst ad mollis tincidunt. Id urna dis arcu dignissim eros pellentesque scelerisque tristique magna?\nPulvinar nostra potenti rhoncus; dictum mauris eleifend nec. Dictum in facilisis cras efficitur congue rutrum. Erat maximus lacinia volutpat ante metus lorem mollis taciti. Eleifend convallis efficitur felis orci pretium bibendum? Orci aliquam lobortis pulvinar malesuada elementum dolor auctor. Leo urna ac parturient himenaeos dolor libero ultricies sem.\nLorem cras tempus velit augue auctor tristique odio nibh. Vitae nunc rutrum at pellentesque curae malesuada condimentum. Molestie habitant morbi nascetur eu; tellus platea ad pellentesque. Aliquam interdum adipiscing hendrerit parturient; consectetur erat. Conubia elementum phasellus rhoncus tincidunt euismod. Taciti nunc placerat lacinia ac sodales porttitor. Nascetur ultricies venenatis in et aenean augue ultricies erat accumsan. Lectus inceptos condimentum ad parturient maximus; luctus nullam vulputate. Cras porttitor mollis viverra hendrerit morbi facilisis.'
  }
]

export const allPosts = [...recentPosts, ...recentPosts]
